name: Download artifact

on: workflow_dispatch

jobs:
  download_artifact:
    name: List all artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ./downloads/
      - name: Display structure of downloaded files
        run: ls -R
      
